Fix for bugs, discovered during testing
applitools/eyes.utils pull request #13
Opened 2016-11-09 17:40 UTC by astappev

- Added RegionProvider
- Added converting position from relative to "screenshot as is" (fix for checkSomethingInFrame)
- bug fixing

2016-12-06 18:02 UTC, dscmg commented
👍 for allowing changes to package.json to update node

2016-12-11 21:41 UTC, danielputerman requested changes

2016-12-11 21:41 UTC, danielputerman commented on src/ImageUtils.js
> +            var destWidth = Math.round(srcImg.width * scale);
You should probably use Math.ceil instead of "round" for dest width/height.

2016-12-13 09:32 UTC, danielputerman requested changes

2016-12-13 09:32 UTC, danielputerman commented on src/ImageUtils.js
> +                    iSrc = Math.round(i * hScale);
You should probably use Math.ceil instead of 'round'.

2016-12-13 09:34 UTC, danielputerman requested changes

2016-12-13 09:34 UTC, danielputerman commented on src/ImageUtils.js
>              width = Math.round(width);
You should probably use Math.ceil

2016-12-13 11:21 UTC, astappev commented on src/ImageUtils.js
> +            var destWidth = Math.round(srcImg.width * scale);
It is don't make any sense, because doBicubicScale doesn't exist anymore and I use doBicubicInterpolation instead.

2016-12-13 11:21 UTC, astappiev commented on src/ImageUtils.js
> +                    iSrc = Math.round(i * hScale);
When I use Math.ceil instead of Math.round I have different results and the results look worst.

2016-12-13 11:21 UTC, astappev commented on src/ImageUtils.js
>              width = Math.round(width);
I am using ```width = Math.ceil(width)``` in latest commit.

2016-12-13 11:22 UTC, danielputerman commented on src/ImageUtils.js
> +            var destWidth = Math.round(srcImg.width * scale);
yea, saw it after moving to next commits 👍

2016-12-13 11:23 UTC, danielputerman commented on src/ImageUtils.js
>              width = Math.round(width);
👍

2016-12-13 11:24 UTC, danielputerman approved these changes

2016-12-13 11:25 UTC, merged